### ISSUE TITLE
Mouse pointer hidden (Ubuntu Wayland) / Cursor icon not changing

### ISSUE THREAD

**Issue by PitiBouchon** [raphamorim/rio#383]
# Issue
After I opened the terminal, when I press the key the cursor disappear, and only re-appear when I move it outside the window. Also when I run with `RIO_LOG_LEVEL=info` there are a bunch of warnings: `[WARN] winit::platform_impl::platform::wayland::window::state Failed to set cursor to Text` when I am moving the cursor inside the terminal

# Config

I using rio version 0.0.30 and also the one from the main branch. I didn't modify the font.

I am on Ubuntu 22.04 using Wayland (and zsh)

**Comment by PitiBouchon** [comment]
Also, when moving the cursor in the window terminal, it doesn't modify its icon (like when moving to the edge to resize the window)

**Comment by RaySlash** [comment]
Do you have cursor set explicitly in the `config.toml`? If not try doing that and report back.

**Comment by PitiBouchon** [comment]
> Do you have cursor set explicitly in the `config.toml`? If not try doing that and report back.
> 
> ```toml
> cursor = "▇"
> blinking-cursor = true
> ```

I've tried to not the cursor, try the bar cursor, set the blinking-cursor to true and false, but it doesn't change anything
I found not issue on **winit** with the filters `is:issue is:open label:"DS - wayland" cursor `

**Comment by RaySlash** [comment]
wierd. Can you post output of `RIO_LOG_LEVEL=debug rio > debug_log-rio.txt` here? while cstpuring replicate your scenerio. Also Can you write exact steps to reproduce your bug in the main post.? Thanks

**Comment by PitiBouchon** [comment]
[rio_cursor_issue.webm](https://github.com/raphamorim/rio/assets/31276594/095b874c-b326-4e1b-be12-0887da4555d2)
[debug_rio.txt](https://github.com/raphamorim/rio/files/13683371/debug_rio.txt)

Step to reproduce : just start the rio terminal (on Ubuntu with gnome and wayland and the default config from Rio)

**Comment by PitiBouchon** [comment]
[debug_rio_log.txt](https://github.com/raphamorim/rio/files/13683506/debug_rio_log.txt)
Here is a log file

**Comment by RaySlash** [comment]
Upon a few googling sessions, I was able to find this https://github.com/wez/wezterm/commit/ecc63e2e5d4938049f9bd36ba70deb379315c3ea in the Wezterm git. Major issue is that the cursor is looking for text type which has less compatibility. One way we could fix is by switching to xterm as wezterm did instead of text. Read the [ISSUE on wez/wezterm](https://github.com/wez/wezterm/issues/532)

Hope this is the culprit: https://github.com/raphamorim/rio/blob/b9c1732a9e26569a2beb9d63eebe9e5f1cc33e9a/frontends/cross-winit/src/router/window/mod.rs#L143

**Comment by raphamorim** [comment]
Good findings @RaySlash 

Wonder if we could use CursorIcon still, they have a map for alternative as well https://github.com/rust-windowing/cursor-icon/blob/main/src/lib.rs#L340

**Comment by RaySlash** [comment]
That should be good. Seems like a solid plan for now. We could setup `alt_names` as a fallback just exactly as its described in [cursor-icon](https://github.com/rust-windowing/cursor-icon/blob/9a8f7d0fea56b6d032041f83ff0142325e848ea0/src/lib.rs#L330C14-L330C14). 🥳

**Comment by Cource** [comment]
I think @PitiBouchon is talking about the *mouse pointer*, and not the cursor in the terminal.
When they start typing in the window, the mouse pointer disappears (which is the default behaviour in the os) and does not become visible again when they move the mouse pointer outside the window.

@PitiBouchon could you check if the behaviour is same in other programs like firefox for eg.? Like, try typing inside a form in firefox (which would cause the pointer to disappear) and then move the pointer.

**Comment by PitiBouchon** [comment]
Yup, I think I used *cursor* instead of *mouse pointer* indeed

The default behavior is what you said, when typing something the pointer disappear and then appear when moving it

I also have the issue with the cursor not changing icon when I move the mouse pointer is near the edges or on the top bar of the window

**Comment by zh4ngx** [comment]
One thing to add to this: for me, the mouse pointer comes back when there is another window on the current desktop. Are you seeing the same behavior? Maybe this detail could be useful?

I am not seeing the same problem in other programs, including Firefox. I am on NixOS+Gnome+Wayland.

**Comment by nyabinary** [comment]
Same issue here, also this is a Wayland-specific issue, not an Ubuntu-specific issue. Related #254

**Comment by PitiBouchon** [comment]
I think this is fixed since the 0.1.X release

**Comment by raphamorim** [comment]
That's great! Yea, I couldn't also reproduce anymore with 0.1.8. Closing this issue for now, thanks for the heads up @PitiBouchon

**Comment by nyabinary** [comment]
> That's great! Yea, I couldn't also reproduce anymore with 0.1.8. Closing this issue for now, thanks for the heads up @PitiBouchon

When typing it disappears (the mouse cursor), which is expected, but when I stop typing the cursor doesn't reappear? I assume this is another issue? :P

**Comment by zh4ngx** [comment]
I'm still getting this issue in 0.1.8 and 0.1.10. It happens before any other windows/apps are open.

**Comment by raphamorim** [comment]
> I'm still getting this issue in 0.1.8 and 0.1.10. It happens before any other windows/apps are open.

1. Wayland as well?

2. Same as the original issue or the one @nyabinary mentioned?

🙏

**Comment by zh4ngx** [comment]
Yup, on NixOS unstable + Wayland. You're right, I think it's more the other issue.

**Comment by raphamorim** [comment]
Thank you for you reply, could open another issue so can keep track on it?

**Comment by zh4ngx** [comment]
No problem, sure

**Comment by nyabinary** [comment]
#647
