### ISSUE TITLE
Font proportions are wrong on startup

### ISSUE THREAD

**Issue by sharph** [raphamorim/rio#659]
Hello!

I am using VictorMono Nerd Font on yesterday's `rio_0.1.12-1_amd64_wayland.deb` release. When I start rio, font proportions look like this:

![Screenshot from 2024-09-08 12-10-04](https://github.com/user-attachments/assets/8f0f799a-0079-405b-af15-6ef1a487382d)

Right as soon as I save the config file (plain touching works too) it adjusts to something that looks more correct:

![Screenshot from 2024-09-08 12-10-33](https://github.com/user-attachments/assets/6314d63e-84a1-4a09-9def-5e5f8e10419e)

But if I close rio and restart it, it reverts to the strange proportions.

**Comment by raphamorim** [comment]
Hey @sharph thank you for the issue, hmmm it looks similar to a bug I fixed today. If instead of save the config, you reduce or increase the font: does it fix as well?

**Comment by sharph** [comment]
Yes, ctrl-(-) and ctrl-+ to resize seems to fix right after a restart.

**Comment by sharph** [comment]
I just built from source and this issue went away, so it may be that bug you fixed.

**Comment by sharph** [comment]
I checked out the 0.1.12 tag and built that and the issue came back, so I'm satisfied that this is fixed in main.

**Comment by raphamorim** [comment]
Thank you for testing! Glad it fixed for you 🙏
