### ISSUE TITLE
iTerm2 image protocol support broken in v0.2.8

### ISSUE THREAD

**Issue by imgurbot12** [raphamorim/rio#999]
Hello, this is my first time using rio but I've run into an issue whilst using [yazi](https://github.com/sxyazi/yazi) to view images in the termal.

iTerm2 image protocol support seems to be broken in v0.2.8 as far as I can tell even on the latest rio-git version.

Rio version: v0.2.8
installation method: arch repostitory `rio` package and AUR `rio-git` (tested using both)
OS: EndeavourOS
DE: Hyprland 0.47.1
imgcat: PyPI

![Image](https://github.com/user-attachments/assets/7aacca68-1a71-46ca-ae95-a77c6ca2be7b)

**Comment by raphamorim** [comment]
Hey @imgurbot12 thanks for the issue,

I tried to reproduce locally without success

<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/a53cf787-2101-44b6-bca0-831ca7ba0ad0" />

**Comment by imgurbot12** [comment]
Hey @raphamorim, thanks for the response.

I tried using chafa and ran into the same issue of an empty response with no rendered image. I notice in your screenshot you're using MacOS. I think this might be a Linux & Wayland specific issue. I tried using both Hyprland and Sway and it failed. I installed the x11 deb version within an Ubuntu VM and that worked whilst the wayland version did not.

**Comment by Quackdoc** [comment]
rio is working fine when I compile myself @imgurbot12 but not when I try it from arch's repos. This seems like it may be a arch specific issue. Likely a good idea to report there. 

I am not sure what arch is doing wrong, but here is the build script for it https://gitlab.archlinux.org/archlinux/packaging/packages/rio/-/blob/main/PKGBUILD?ref_type=heads

**Comment by raphamorim** [comment]
Thank you @Quackdoc for the comment (good username btw)

Yea, the reason it's probably is using a wrong version of copa dependency under the hood, since copa iterm2 fix was just a minor bump `0.2.x`. cc @orhun legend

**Comment by imgurbot12** [comment]
@raphamorim if this issue is valuable for tracking the AUR package fix or something then feel free to reopen, but it sounds to me like the solution is on its way and has been resolved. Thanks everyone :)

**Comment by orhun** [comment]
> a wrong version of copa dependency under the hood, since copa iterm2 fix was just a minor bump

Can you link to the release? Should we expect a new version of Rio for fixing this in the package?

**Comment by raphamorim** [comment]
It was already released in v0.2.2 if i am not mistaken

**Comment by Quackdoc** [comment]
the issue occurs when `--all-features` are passed. And it does still occur on latest git as of this comment. not sure if this warrants re-opening due to --all-features inherently being a little sketchy. If you want `--all-features` to work then this should indeed be re-opened, if not I will report it to arch package maintainer
